//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviciosrest
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int codpro { get; set; }
        public string nompro { get; set; }
        public string despro { get; set; }
        public decimal prepro { get; set; }
        public decimal canpro { get; set; }
        public bool estpro { get; set; }
        public int codcat { get; set; }
    
        public virtual categoria categoria { get; set; }
    }
}
